---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-07-09 - 08:02:05 +0000
  labels:
    app.kubernetes.io/name: driver-service
    app.kubernetes.io/version: 1.0.0
  name: driver-service
  namespace: foody-clone
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: driver-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-07-09 - 08:02:05 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: driver-service
  name: driver-service
  namespace: foody-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: driver-service
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-07-09 - 08:02:05 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: driver-service
      namespace: foody-clone
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: driver-service:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: driver-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
