---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-07-09 - 08:02:58 +0000
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/version: 1.0.0
  name: payment-service
  namespace: foody-clone
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-07-09 - 08:02:58 +0000
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/version: 1.0.0
  name: payment-service
  namespace: foody-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-07-09 - 08:02:58 +0000
      labels:
        app.kubernetes.io/name: payment-service
        app.kubernetes.io/version: 1.0.0
      namespace: foody-clone
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: payment-service:1.0.0
        imagePullPolicy: IfNotPresent
        name: payment-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
