# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - 
        uses: actions/checkout@v2
        name: Checkout frontend
        with:
          path: spending-money
          clean: false
      - 
        uses: actions/checkout@v2
        name: Checkout backend
        with:
          repository: aavn-ct-workshop/aavn-ct-workshop.github.io
          ref: master
          path: spending-money-backend
          token: ${{ secrets.REPO_ACCESS }}
          clean: false
      -
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Build frontend
        run: |
          cd spending-money
          npm ci && npm run build --if-present
      - 
        name: Copy file
        run: pwd && ls && cp -rv foody-clone/dist/* aavn-ct-workshop.github.io
      - 
        name: Commit files
        run: |
          cd spending-money-backend
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          date > deployment.version
          git status
          git add --all
          git commit -m "Deploy new frontend version `date`" -a
          git push
#       -
#         name: Deploy to GitHub Pages
#         if: success()
#         uses: crazy-max/ghaction-github-pages@v2
#         with:
#           repo: aavn-ct-workshop/aavn-ct-workshop.github.io
#           target_branch: main
#           build_dir: dist
#           keep_history: true
#         env:
#           GH_PAT: ${{ secrets.REPO_ACCESS }}
